version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    IMAGE_REPO_NAME: brain-tasks-app
    IMAGE_TAG: latest
    PUBLIC_ECR_URI: public.ecr.aws/t5e7w0l5/brain-tasks-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...

      - aws --version
      - docker --version

      # Login to Public ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 050083685935.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`

      # Build Docker image
      - docker build -t brain-tasks-app .

      # Tag image
      - docker tag brain-tasks-app:latest 050083685935.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Pushing Docker image to Public ECR...

      # Push image
      - docker push 050083685935.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
