version: 0.2

phases:

  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - REGION=ap-south-1

      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/brain-tasks-app

      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - IMAGE_TAG=latest

  build:
    commands:
      - echo Build started

      - docker build -t brain-tasks-app .

      - docker tag brain-tasks-app:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image...

      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo Updating kubeconfig...

      - aws eks update-kubeconfig --region ap-south-1 --name brain-eks-cluster

      - kubectl apply -f deployment.yaml

      - kubectl apply -f service.yaml

      - kubectl rollout restart deployment brain-tasks-deployment

artifacts:
  files:
    - '**/*'
